server:
  port: 8080

tqconfig:
  type_icon1: /static/images/pdd.png
  type_icon2: /static/images/pdd.png
  detail_share_title:
    - 这个太便宜，只要
    - 图里这个只要
    - 分享给你看看，只要
    - 不是好货不分享，仅售
    - 买它！只要
    - 好物不贵
    - 领券仅需
  index_share_title: 芝麻领惠，先领券再买更实惠
  materials:
    - id: 28027
      description: 综合
    - id: 3761
      description: 食品
    - id: 3763
      description: 美妆个护
    - id: 28029
      description: 服饰
    - id: 28028
      description: 数码家电
    - id: 27798
      description: 家居家装
    - id: 27454
      description: 母婴
  banners:
    - banner: '//img.alicdn.com/i1/2201188731272/O1CN010dPWX61LGcLysrN9d_!!2201188731272.jpg'
      guide_imgs:
        - '//img.alicdn.com/i3/1030582371/O1CN015BY3x01TNxfA8kJgB_!!1030582371.jpg'
        - '//img.alicdn.com/i1/1030582371/O1CN01yyvgae1TNxf6kYHpH_!!1030582371.jpg'
        - '//img.alicdn.com/i3/1030582371/O1CN019gqUlp1TNxf2p6u5U_!!1030582371.jpg'
        - '//img.alicdn.com/i3/1030582371/O1CN017ZnNoo1TNxf1UM6Ct_!!1030582371.jpg'
    - banner: '//img.alicdn.com/i1/2201188731272/O1CN01hyjchT1LGcM2CPSqP_!!2201188731272.jpg'
      guide_imgs:
        - '//img.alicdn.com/i3/720250651/O1CN01wLCZ5J1GgCLop4jDr_!!720250651.jpg'
        - '//img.alicdn.com/i2/720250651/TB2pznWbYGYBuNjy0FoXXciBFXa_!!720250651.png'
        - '//img.alicdn.com/i3/720250651/O1CN01xyagpO1GgCMYBIAmf_!!720250651.jpg'
