server:
  port: 8080

tqconfig:
  type_icon1: /static/images/tianmao.png
  type_icon2: /static/images/taobao.png
  detail_share_title:
    - 这个太便宜，只要
    - 图里这个只要
    - 分享给你看看，只要
    - 不是好货不分享，仅售
    - 买它！只要
    - 好物不贵
    - 领券仅需
  index_share_title: 芝麻领惠，先领券再买更实惠
  materials:
    - id: 31362
      description: 热卖
    - id: 27451
      description: 食品
    - id: 3763
      description: 美妆个护
    - id: 4092
      description: 服饰
    - id: 9645
      description: 数码家电
    - id: 27798
      description: 家居日用
    - id: 27454
      description: 母婴
  banners:
    - banner: 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/banner1.png'
      guide_imgs:
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/use1.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/use2.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/use3.jpg'
    - banner: 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/start.png'
      guide_imgs:
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide1.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide2.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide3.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide4.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide5.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide6.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide7.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide8.jpg'
