server:
  port: 8080

tqconfig:
  type_icon1: /static/images/tianmao.png
  type_icon2: /static/images/taobao.png
  detail_share_title:
    - 这个太便宜，只要
    - 图里这个只要
    - 分享给你看看，只要
    - 不是好货不分享，仅售
    - 买它！只要
    - 好物不贵
    - 领券仅需
  index_share_title: 芝麻领惠，先领券再买更实惠
  materials:
    - id: 28028
      description: 热卖
    - id: 27451
      description: 食品
    - id: 28029
      description: 服饰
    - id: 9638
      description: 鞋包饰品
    - id: 8169
      description: 睡衣内衣
    - id: 9645
      description: 家电
    - id: 3760
      description: 母婴
  recommends:
    - id: 28027
      description: 精选
      path: '/static/images/jingxuan.png'
    - id: 3761
      description: 零食
      path: '/static/images/lingshi.png'
    - id: 9646
      description: 女装
      path: '/static/images/nvzhuang.png'
    - id: 8040
      description: 个护
      path: '/static/images/gehu.png'
    - id: 9641
      description: 运动
      path: '/static/images/yundong.png'
  banners:
    - banner: 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/tb_banner1.png'
      guide_imgs:
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide1.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide2.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide3.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide4.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide5.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide6.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide7.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/guide8.jpg'
  pdd_banners:
    - banner: 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/pdd_banner1.png'
      guide_imgs:
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/pdd_guide1.jpg'
        - 'https://coldcoder.oss-cn-beijing.aliyuncs.com/taoquan/banner/pdd_guide2.jpg'